### ISSUE TITLE
 jupyter-lab-provider@0.8.11 isn't compatible with the current JupyterLab

### ISSUE THREAD

**Issue by laborg** [JuliaGizmos/WebIO.jl#400] opened 2020-04-10 16:32 UTC
Apparently jupyter-lab-provider@0.8.11 isn't compatible with jupyterlab >2:

```
Node v13.12.0

Yarn configuration loaded.
> /usr/bin/npm pack @webio/jupyter-lab-provider@0.8.11
npm notice 
npm notice 📦  @webio/jupyter-lab-provider@0.8.11
npm notice === Tarball Contents === 
npm notice 16.6kB dist/labextension.js
npm notice 959B   package.json        
npm notice 438B   README.md           
npm notice === Tarball Details === 
npm notice name:          @webio/jupyter-lab-provider             
npm notice version:       0.8.11                                  
npm notice filename:      webio-jupyter-lab-provider-0.8.11.tgz   
npm notice package size:  5.3 kB                                  
npm notice unpacked size: 18.0 kB                                 
npm notice shasum:        88d4a46fe3e23e1adcd20d5df79bdad8c860ef23
npm notice integrity:     sha512-4masN5DAg5Qrq[...]jESB6J58c5Z9g==
npm notice total files:   3                                       
npm notice 
webio-jupyter-lab-provider-0.8.11.tgz

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 1550, in _install_extension
    raise ValueError(msg)

ValueError: 
"@webio/jupyter-lab-provider@0.8.11" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/application
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/docmanager
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/notebook
>=2.0.2 <2.1.0          >=1.0.1 <2.0.0 @jupyterlab/rendermime
>=5.0.2 <5.1.0          >=4.0.1 <5.0.0 @jupyterlab/services

```

**Comment by travigd** [comment] 2020-04-10 17:03
Duplicate of #397

**Closed by travigd** 2020-04-10 17:03 UTC
