### ISSUE TITLE
WebIO not detected.

### ISSUE THREAD

**Issue by tamasgal** [JuliaGizmos/WebIO.jl#236] opened 2018-11-30 14:53 UTC
I recently filed an issue in `Interact.jl` (https://github.com/JuliaGizmos/Interact.jl/issues/280) since I was not able to use it, but it's obviously an issue with `WebIO.jl`.

If I try to use it in Jupyter, I get the error `WebIO not detected.` and the `deps/build.log` is empty. I also tried to rebuild it but it gives no error whatsoever:

```
(v1.0) pkg> build WebIO
  Building WebIO → `~/.julia/packages/WebIO/NYISm/deps/build.log`

(v1.0) pkg>
```

Any ideas how to debug this? I am running Julia 1.0 and can't get it to work on macOS Mojave.

**Comment by Fruktus** [comment] 2018-12-11 13:06
Check if you have nbextensions installed in jupyter, this solved my problem with this issue

**Comment by truefalsename** [comment] 2018-12-12 09:54
Update: I reinstalled WebIO after having installed nbextensions and I can now see the plots, however, whenever I open a notebook I see a warning saying that WebIO was loaded on an ad-hoc basis, despite the fact that the corresponding extension is active prior to loading the notebook.

Plots also appear buggy: i cannot rotate 3d plots at all for instance

**Comment by truefalsename** [comment] 2018-12-13 08:33
another update:

PS C:\Users\lucam\.jupyter>  jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\lucam\.jupyter\nbconfig
    notebook section
      webio/main enabled
      - Validating: problems found:
        - require?  X webio/main
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: c:\program files\python37\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Comment by tamasgal** [comment] 2018-12-13 09:18
@Fruktus that was it thanks!

    pip install jupyter_contrib_nbextensions

**Comment by travigd** [comment] 2018-12-21 23:31
Hi, all, are y'all still having issues?

If so, try the latest on the webio-retool branch (should also be available as `v0.6.2` very soon).
```julia
]add WebIO#webio-retool
```

I added a number of Jupyter notebook stability fixes.

**Comment by shashi** [comment] 2018-12-22 16:33
You might need to restart jupyter once you install or build WebIO... Did you try that @truefalsename?

**Comment by truefalsename** [comment] 2018-12-23 09:19
I tried, didn't help. When I open a julia noebook I still get the same 404 as before and when I try to plot something via plotlyjs either I get "WebIO not detected" or I get a plot in a separate electron window (should have been in notebook) and the plot is super buggy. cannot rotate/interact with 3d plots and the navigation buttons do random things.

**Comment by travigd** [comment] 2018-12-23 13:17
I think the issue is perhaps a false assumption about where nbextensions live in Windows.

I think the `jupyter-nbextension` command has some way to list the directory where extensions live. The build process should be updated to include that directory.

**Comment by travigd** [comment] 2018-12-28 01:47
Can you run `jupyter --paths` and see what it spits out?

**Comment by truefalsename** [comment] 2018-12-28 06:41
Hello, 
sure, sorry for the slow reply  -- have been digesting.

Here is the output

 config:
    C:\Users\lucam\.jupyter
    c:\users\lucam\appdata\local\programs\python\python37\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\lucam\AppData\Roaming\jupyter
    c:\users\lucam\appdata\local\programs\python\python37\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\lucam\AppData\Roaming\jupyter\runtime

**Comment by travigd** [comment] 2019-03-28 02:16
This should be fixed now that WebIO installs the extension to the correct OS-specific location (when using master -- the "latest" version, 0.7.0, should work regardless). If you have issues still, please let me know, but I'm closing this for now.

**Closed by travigd** 2019-03-28 02:16 UTC

**Comment by hhaensel** [comment] 2019-04-18 09:39
For me it still doen't work.
I suppose, that 
       ``` return joinpath(homedir(), "%APPDATA%", "jupyter")```
in https://github.com/JuliaGizmos/WebIO.jl/blob/master/deps/build.jl#L64 should be replaced by
       ``` return joinpath("%APPDATA%", "jupyter")```
(working on Windows 7; interestingly, in the address bar of the explorer window the output of `joinpath(homedir(), "%APPDATA%", "jupyter")` resolves fine, whereas it doesn't on the command line)

**Comment by sschuldenzucker** [comment] 2019-05-21 20:46
Hi! I just spotted another incarnation of this issue on Windows 10.

I had the same problem (not working and "problems found" in `jupyter nbextension list`), but I found a folder at the *literal* (not further expanded) path: `C:\Users\steff\%APPDATA%\jupyter\nbextensions\webio` ("steff" is my user name; the folder is literally called "%APPDATA%").

It looks like expansion in https://github.com/JuliaGizmos/WebIO.jl/blob/119a22b2840111639fbfb9081f8a28f0ae6008b7/deps/build.jl#L64 is not working. That's the only place where `%APPDATA%` is used in the build script, at least.

I then copied the folder to the *expanded* path `%APPDATA%\jupyter\nbextensions\webio` (in my case that's `C:\Users\steff\AppData\Roaming\jupyter\nbextensions`) and since then everything works perfectly.

**Comment by pfitzseb** [comment] 2019-05-22 09:33
That `%APPDATA%` issue will be fixed with https://github.com/JuliaGizmos/WebIO.jl/pull/286.

**Comment by travigd** [comment] 2019-05-25 21:31
That PR has been merged.

If you're still having issues (on Windows), please build WebIO again (feel free to delete the extraneous `%APPDATA%` directory that we accidentally created). If you're **still** having issues, please open a new issue.
