### ISSUE TITLE
Latest update seems to have broken PlotlyJS

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#227] opened 2018-11-16 16:28 UTC
With PlotlyJS v0.12.0 and WebIO v0.6.0, this code displays a blank in IJulia

```julia
using PlotlyJS, PlotlyBase
PlotlyJS.plot([PlotlyJS.scatter(x=[1,2], y=[2,3])])
```

I did `build WebIO` as recommended, and I restarted the notebook server, but no dice. Then when I pinned WebIO@v0.4.2, it worked once more. Can anyone reproduce?

cc. @sglyon

**Comment by sglyon** [comment] 2018-11-16 16:34
Oh no 😱 !

Was this in the jupyter notebook or jupyterlab?

**Comment by cstjean** [comment] 2018-11-16 16:35
Notebook.

**Comment by rdeits** [comment] 2018-11-16 18:07
Perhaps related to #225?

**Comment by samtkaplan** [comment] 2018-11-16 18:47
I can reproduce.  I also solved the issue by pinning WebIO to v0.4.2.

**Comment by JobJob** [comment] 2018-11-20 11:33
I can replicate in Atom/Jupyter, and `using Pkg; Pkg.add(PackageSpec(name="WebIO", version="v0.4.2"))` fixes it.

@sglyon - might be good to upper bound WebIO to v0.4.2 until it's fixed.

**Comment by JobJob** [comment] 2018-11-20 11:35
P.S. I'm not up to date with the latest but @travigd might have a clue what's up.

**Comment by sglyon** [comment] 2018-11-20 12:33
@JobJob thanks for the tip (and for commenting over in PlotlyJS.jl). i think this is probably a good idea.

Does anyone here know what might be the problem?

**Comment by pfitzseb** [comment] 2018-11-20 12:40
In Juno I see
```
Cannot set property 'Plotly' of undefined Evaluating http://localhost:8279/assetserver/d758b17599603129b8ecf571b510408665868d7b-plotly_webio.bundle.js
```
so there might be some incompatibility of that JS code with the current WebIO code?

**Comment by sglyon** [comment] 2018-11-20 12:51
The source for that is here: https://github.com/sglyon/PlotlyJS.jl/blob/master/assets/index.js

It must be that WebIO.CommandSets doesn't exist anymore?

**Comment by pfitzseb** [comment] 2018-11-20 12:54
Yep:
![image](https://user-images.githubusercontent.com/6735977/48774883-ba205f00-eccb-11e8-9c56-612298259776.png)
Not sure what you could use now though, haven't looked through the frontend code yet.

**Comment by travigd** [comment] 2018-11-20 14:01
Hi, yes. Will work on this this week (unless someone else wants to try their hand at writing something! 😅).

Initial thoughts are that "polyfilling" this behavior will be a good stop gap, but registering global command sets doesn't seem like the best way to do things imho because globals are bad™.

**Comment by sglyon** [comment] 2018-11-20 14:44
@travigd I am 100% happy to not add this to a global.

When I wrote that code, that was the suggested way to extend the js side of webio.

If there is a better approach for it now please let me know and I'm happy to adjust. The main need I have is to be able to load a js function that I end up calling from my WebIO Julia code

**Comment by pfitzseb** [comment] 2018-11-20 15:06
Couldn't you just add that to `window`?

**Comment by travigd** [comment] 2018-11-20 15:07
@sglyon How does [this (see my first comment)](https://github.com/JuliaGizmos/WebIO.jl/issues/216?_pjax=%23js-repo-pjax-container#issuecomment-440305238) look? Combined with the async dependency management we talked about in Slack (I can summarize here if you weren't present, and I'd like to open an issue for it too soon).

**Comment by travigd** [comment] 2018-11-20 15:54
@pfitzseb Generally, adding things to `window` is a bad™ thing and I absolutely don't think it's something we should encourage, especially for library developers.

I'm not going to chastize anyone for using window globals in their own notebooks/apps, especially given that generally people aren't coming to WebIO as web developers, but I do think we should push people towards web best practices (_especially_ for widely used packages).

**Comment by pfitzseb** [comment] 2018-11-20 15:59
Fair enough. I only suggested that because I thought basically all WebIO frontends wrap widgets in an iframe or a similar construct, where adding things to `window` shouldn't matter much.

**Comment by travigd** [comment] 2018-11-20 16:21
Unfortunately, no. This is something I toyed with briefly but the memory usage is far too high to be workable (every iframe is equivalent to having a new tab open).

**Comment by cstjean** [comment] 2019-02-04 15:03
Any news on this front?

**Comment by travigd** [comment] 2019-03-28 18:06
Should be fixed by https://github.com/sglyon/PlotlyJS.jl/pull/276 on WebIO#master.

**Closed by travigd** 2019-03-28 18:06 UTC
Labels: bug
